### ISSUE TITLE
Token detection failing

### ISSUE THREAD

**Issue by stevehipwell** [CramBL/dependabot-changelog-writer#75]
I get the following error message when I add markdown styling around the changelog entry pattern tokens.

> /home/runner/work/_temp/77e673da-ae35-48a4-ab38-6649cda9ba0e.sh: line 1: [old]: command not found
/home/runner/work/_temp/77e673da-ae35-48a4-ab38-6649cda9ba0e.sh: line 1: [new]: command not found
Error: Missing token: [old]
Error: Process completed with exit code 1.

This is my configuration.

```yaml
      - name: Changelog
        uses: crambl/dependabot-changelog-writer@b337c10b931c96fa5b44e6d2e25c1cd693c5eb36 # v1.1.0
        with:
          push-token: ${{ steps.sts.outputs.token }}
          commit-message: "chore: Update changelog for Dependabot"
          changelog: ./CHANGELOG.md
          section-header: "### Changes"
          changelog-entry-pattern: "Update _[dep]_ from `[old]` to `[new]`. ([pr-link]) _@dependabot_"
          push-changes: true
```
